server:
  port: 8084
spring:
  application:
    name: generate-credit-card-application-service
  datasource:
    url: jdbc:postgresql://localhost:5432/credit-card-details
    username: root
    password: root
  jpa:
    generateDdl: true
    showSql: false
  cloud:
    stream:
      function:
        definition: generateCreditCard
      bindings:
        verifyCreditCardApplication-in-0:
          destination: CreditCardVerification
          group: credit-card
        verifyCreditCardApplication-out-0:
          destination: CreditCardVerification
          group: credit-card
